name: SetCommandBlock
main: xyz.zinntikumugai.pl.setcommandblock.SetCommandBlock
version: 0.0.1
author: zinntikumugai
default-permission: false

commands:
  setcommandblock:
    description: ""
    permission: setcommandblock.use
    

permissions:
  setcommandblock.use:
    description: ""
    default: false

  setcommandblock.put:
    description: ""
    children:
      setcommandblock.use: true
    default: false

  setcommandblock.commandset:
    description: ""
    children:
      setcommandblock.use: true
    default: false

  setcommandblock.commandremove:
    description: ""
    children:
      setcommandblock.use: true
    default: false
